defaults: &defaults
  keystone:
    ip: localhost 
    port: 5000
    admin_port: 35357
    username: admin
    password: portland 
    tenant: admin
  
  region: RegionOne
  publicurl: localhost:3001
  adminurl: localhost:3001
  internalurl: localhost:3001

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
