defaults: &defaults
  keystone:
    ip: 171.71.119.10
    port: 5000
    admin_port: 35357
    username: admin
    password: nova
    tenant: admin
  
  region: RegionOne
  publicurl: 171.71.119.10:3001
  adminurl: 171.71.119.10:3001
  internalurl: 171.71.119.10:3001

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
